Add changes for 1.1.1
redhat-developer/vscode-quarkus pull request #125
Opened 2019-10-22 16:53 UTC by xorye

![image](https://user-images.githubusercontent.com/20326645/67310014-f2778100-f4ca-11e9-849d-b2e71d72e910.png)

Signed-off-by: David Kwon <dakwon@redhat.com>

2019-10-22 17:29 UTC, fbricon requested changes

2019-10-22 17:29 UTC, fbricon commented on CHANGELOG.md
> +## 1.1.1 (October 21, 2019)
October 23

2019-10-22 17:29 UTC, fbricon commented on CHANGELOG.md
> + * Welcome page opens on the side. See [#120](https://github.com/redhat-developer/vscode-quarkus/pull/120)
Should be an enhancement

2019-10-22 17:29 UTC, fbricon commented on CHANGELOG.md
> + * Preserve focus when welcome page is displayed. See [#124](https://github.com/redhat-developer/vscode-quarkus/pull/124)
should be a bug fix

2019-10-22 18:16 UTC, xorye commented
fixed

2019-10-23 15:33 UTC, fbricon commented on CHANGELOG.md
> + * Preserve focus when welcome page is displayed. See [#124](https://github.com/redhat-developer/vscode-quarkus/pull/124)
should link to https://github.com/redhat-developer/vscode-quarkus/issues/73 instead

2019-10-23 15:43 UTC, xorye commented
changed link to #73

2019-10-23 16:15 UTC, fbricon commented on CHANGELOG.md
> + * Welcome page opens on the side. See [#120](https://github.com/redhat-developer/vscode-quarkus/pull/120)
change about new command id is missing

2019-10-23 16:56 UTC, xorye commented on CHANGELOG.md
> + * Welcome page opens on the side. See [#120](https://github.com/redhat-developer/vscode-quarkus/pull/120)
added

2019-10-23 17:59 UTC, merged