CHANGELOG for 1.2.0
redhat-developer/vscode-quarkus pull request #153
Opened 2019-11-13 15:52 UTC by angelozerr

CHANGELOG for 1.2.0

Signed-off-by: azerr <azerr@redhat.com>

2019-11-13 18:15 UTC, fbricon requested changes
A bunch of issues seems to be missing from https://github.com/redhat-developer/vscode-quarkus/issues?utf8=%E2%9C%93&q=milestone%3A1.2.0+

2019-11-13 18:17 UTC, fbricon commented
some issues are from the 1.1.1 release

2019-11-14 16:25 UTC, fbricon commented on CHANGELOG.md
> + * Add quarkus extension to a gradle project. See [#112](https://github.com/redhat-developer/vscode-quarkus/issues/112)
Gradle

2019-11-14 16:25 UTC, fbricon commented on CHANGELOG.md
> + * Create new Gradle project. See [#108](https://github.com/redhat-developer/vscode-quarkus/issues/108)
Create a new Gradle project

2019-11-14 18:24 UTC, angelozerr commented on CHANGELOG.md
> + * Add quarkus extension to a gradle project. See [#112](https://github.com/redhat-developer/vscode-quarkus/issues/112)
@fbricon updated

2019-11-14 18:25 UTC, angelozerr commented on CHANGELOG.md
> + * Create new Gradle project. See [#108](https://github.com/redhat-developer/vscode-quarkus/issues/108)
@fbricon updated

2019-11-15 15:12 UTC, angelozerr commented
@fbricon anything else?

2019-11-15 15:55 UTC, fbricon commented
let's hold on to that one until we have the proper release date

2019-11-20 16:29 UTC, merged