Add extension description toggle button
redhat-developer/vscode-quarkus pull request #165
Opened 2019-11-28 22:56 UTC by xorye

This PR is not ready yet.
When it is ready, the PR should fix #164. 

This PR adds a button on the top right that toggles the extensions selection list. The button's colours are different for a dark and light theme.
![demo gif](https://raw.githubusercontent.com/xorye/gifs/master/quarkus-ls/PR/extdesc.gif?token=AE3CR5JWSS3HDGZQX3TOASK55GFJW)

Currently, clicking the button while you are scrolled all the way down, would bring you back to the top. The VS Code api does not provide a clear way to fix this.

This PR also introduces a user config setting to set whether or not the descriptions should appear or not.

Signed-off-by: David Kwon <dakwon@redhat.com>

2019-12-02 19:35 UTC, xorye commented
This PR is ready for review. 

As an aside: the icon's SVG was from this website: https://feathericons.com/?query=info

2019-12-04 13:45 UTC, fbricon requested changes
Except for the small change to make in the readme, this is excellent, nice work @xorye!

2019-12-04 13:45 UTC, fbricon commented on README.md
> +* `quarkus.tools.starter.showExtensionDescriptions`: Determines whether to show the Quarkus extension descriptions when selecting Quarkus extensions. Default is `true`.
move to Since 1.3.0 section

2019-12-04 14:13 UTC, xorye commented
@fbricon thank you! Fixed

2019-12-04 14:27 UTC, merged