Tests for 'Generate a new Quarkus Project'
redhat-developer/vscode-quarkus pull request #172
Opened 2019-12-09 02:48 UTC by xorye

This PR provides 6 tests that test the 'Generate a new Quarkus Project' command.

To run the tests, either select the 'VS Code UI Extension Tests' debug config:
![image](https://user-images.githubusercontent.com/20326645/70402942-29fea600-1a03-11ea-8451-8746c6b96ca6.png)

or, run
`npm run test-compile && extest setup-and-run 'out/test/vscodeUiTest/suite/*.js' -u`

Using the current master branch of [vscode-extension-tester](https://github.com/redhat-developer/vscode-extension-tester), this PR currently works on Fedora 30.

Currently for Windows 10, running the tests from the command line does not work.
Running the tests within VS Code works. 

For Mac, there are two tests that do not work because of the lack of support for Mac's native folder selection window: https://github.com/redhat-developer/vscode-extension-tester/issues/40

2019-12-23 08:37 UTC, fbricon commented
@xorye Travis build fails

2020-01-31 10:35 UTC, fbricon commented
CLI build fails:
```

> vscode-quarkus@1.3.0 ui-test /Users/fbricon/Dev/projects/vscode-quarkus
> npm run test-compile && extest setup-and-run 'out/test/vscodeUiTest/suite/*.js' -u


> vscode-quarkus@1.3.0 test-compile /Users/fbricon/Dev/projects/vscode-quarkus
> tsc -p ./

VS Code exists in local cache, skipping download
ChromeDriver 76.0.3809.126 exists in local cache, skipping download

> vscode-quarkus@1.3.0 vscode:prepublish /Users/fbricon/Dev/projects/vscode-quarkus
> webpack --mode production

Hash: 1374edbd6b9383b9c55a
Version: webpack 4.32.2
Time: 8933ms
Built at: 2020-01-31 11:33:01 a.m.
           Asset      Size  Chunks             Chunk Names
    extension.js  1.14 MiB       0  [emitted]  main
extension.js.map  3.68 MiB       0  [emitted]  main
Entrypoint main = extension.js extension.js.map
  [0] external "path" 42 bytes {0} [built]
  [1] external "vscode" 42 bytes {0} [built]
 [28] ./src/definitions/constants.ts 2.21 KiB {0} [built]
 [36] ./src/QuarkusConfig.ts 3.35 KiB {0} [built]
 [58] ./src/QuarkusContext.ts 3.23 KiB {0} [built]
[144] ./src/extension.ts 8.1 KiB {0} [built]
[145] ./src/languageServer/requirements.ts 4.58 KiB {0} [built]
[177] ./src/addExtensions/addExtensionsWizard.ts 4.96 KiB {0} [built]
[345] ./src/debugging/terminateProcess.ts 5.14 KiB {0} [built]
[347] ./src/generateProject/generationWizard.ts 11.9 KiB {0} [built]
[376] ./src/languageServer/javaServerStarter.ts 2.49 KiB {0} [built]
[385] ./src/debugging/startDebugging.ts 2.78 KiB {0} [built]
[389] ./src/webviews/WelcomeWebview.ts 5.33 KiB {0} [built]
[393] ./src/lsp-commands.ts 3.43 KiB {0} [built]
[394] ./src/yaml/YamlSchema.ts 6.17 KiB {0} [built]
    + 381 hidden modules

WARNING in ./node_modules/ejs/lib/ejs.js 917:4-22
require.extensions is not supported by webpack. Use a loader instead.
 @ ./src/webviews/WelcomeWebview.ts 27:12-26
 @ ./src/extension.ts

WARNING in ./node_modules/ejs/lib/ejs.js 918:2-20
require.extensions is not supported by webpack. Use a loader instead.
 @ ./src/webviews/WelcomeWebview.ts 27:12-26
 @ ./src/extension.ts
 DONE  Packaged: /Users/fbricon/Dev/projects/vscode-quarkus/vscode-quarkus-1.3.0.vsix (90 files, 8.29MB)
Installing extensions...
Extension 'vscode-quarkus-1.3.0.vsix' was successfully installed.
Installing extensions...
Extension 'api-handler.vsix' was successfully installed.


Writing code settings to /Users/fbricon/Dev/projects/vscode-quarkus/test-resources/settings/User/settings.json
  Project generation tests
    1) should open project generation wizard

Shutting down the browser
Uninstalling vscode-extension-tester.api-handler...
Extension 'vscode-extension-tester.api-handler' was successfully uninstalled!
Uninstalling redhat.vscode-quarkus...
Extension 'redhat.vscode-quarkus' was successfully uninstalled!

  0 passing (29s)
  1 failing

  1) Project generation tests
       should open project generation wizard:
     Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/fbricon/Dev/projects/vscode-quarkus/out/test/vscodeUiTest/suite/projectGenerationTest.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

I can see the command being typed in the palette, but then nothing happens

2020-02-03 22:31 UTC, xorye commented
@fbricon vscode-extension-tester 2.3.0 introduces this new dependency https://www.npmjs.com/package/@nut-tree/nut-js to improve mac support.

nut-js has some prerequisites: https://www.npmjs.com/package/@nut-tree/nut-js#prerequisites which is probably why the Travis test for Linux is failing.

2020-02-03 22:47 UTC, xorye commented
Here is what I did to get the tests working on mac:

1. Change the node version to 12.12. nut-js has an issue on macs: https://github.com/nut-tree/nut.js/issues/98#issuecomment-571494625

2. Give accessibility permissions to the terminal (iTerm in this case)
![image](https://user-images.githubusercontent.com/20326645/73697484-a97bbf00-46ac-11ea-913f-6cf7c26933c5.png)

3. Run `npm i` and `npm run ui-tests` in the same terminal application as step 2.

When running the ui tests, it would be best to disable all other extensions so that they don't interfere with the testing.

Running the ui tests will create a `vscode-quarkus/test-resources` directory, which stores things (like the VS Code test installation) for the tests. When changing branches, that directory should be deleted because if not, `vsce package` will result in an error. To fix the error, `test-resources` should be added to `.vscodeignore`, which this PR does already: 
https://github.com/redhat-developer/vscode-quarkus/blob/75979097ee8c17d80a625c9df2ec976aebb7e7dc/.vscodeignore#L11

2020-02-18 19:32 UTC, xorye commented
@fbricon its finally working on both ubuntu 16.04  and mac, but on ubuntu, the folder choosing test seems to work/stop working randomly

2020-02-18 22:15 UTC, xorye commented
I've updated the contributing guide to mention about testing.

I've also changed the test commands:
Run regular vscode tests: `npm test`
Run UI tests: `npm run test-ui`
Run both: `npm run test-all`

2020-02-20 17:36 UTC, fbricon requested changes

2020-02-20 17:36 UTC, fbricon commented on src/test/vscodeUiTest/suite/projectGenerationTest.ts
> +  it('should displays extensions without duplicates', async function() {
should display

2020-02-20 18:49 UTC, xorye commented on src/test/vscodeUiTest/suite/projectGenerationTest.ts
> +  it('should displays extensions without duplicates', async function() {
fixed

2020-02-21 09:05 UTC, angelozerr commented
@xorye please resolve conflicts

2020-02-21 15:27 UTC, xorye commented
Fixing conflict

2020-02-21 15:29 UTC, angelozerr commented
@xorye please fix the new conflict please.

2020-02-21 15:38 UTC, xorye commented
fixed

2020-02-21 16:33 UTC, merged

2020-02-21 16:33 UTC, fbricon commented
Thanks @xorye!