Create contributing guide
redhat-developer/vscode-quarkus pull request #24
Opened 2019-08-08 13:19 UTC by xorye

Fixes [quarkus-ls #8](https://github.com/redhat-developer/quarkus-ls/issues/8). 

CONTRIBUTING.md is the first draft for the contributing guide. 
In the markdown file, I briefly explain how communication works, how to build the projects and how to debug.

Please let me know if anything could be explained better, or if anything should be added.

Signed-off-by: David Kwon <dakwon@redhat.com>

2019-08-08 22:01 UTC, fbricon requested changes
That's pretty good! A bunch of typos to fix though

2019-08-08 22:01 UTC, fbricon commented on CONTRIBUTING.md
> +Step 2. Quarkus langauge server checks its cache if completion options
language

2019-08-08 22:01 UTC, fbricon commented on CONTRIBUTING.md
> +for the current Quarkus project exists.
(completion options) exist

2019-08-08 22:01 UTC, fbricon commented on CONTRIBUTING.md
> +* If it does not exist, the Quarkus langauge server sends a
language

2019-08-08 22:01 UTC, fbricon commented on CONTRIBUTING.md
> +to the Quarkus langauge server.
language

2019-08-08 22:01 UTC, fbricon commented on CONTRIBUTING.md
> +Step 6. Quarkus langauge server receives the information, adds it
language

2019-08-08 22:01 UTC, fbricon commented on CONTRIBUTING.md
> +### Debugging the Quarkus langauge server:
language

2019-08-09 14:21 UTC, xorye commented
Thanks @fbricon, I made the changes.

2019-08-13 14:53 UTC, merged

2019-08-13 14:54 UTC, angelozerr commented
I follow the documentation and it works like a charm, well done @xorye !