Handle failure to access API endpoint
redhat-developer/vscode-quarkus pull request #27
Opened 2019-08-09 16:34 UTC by xorye

Fixes #22

Here are the two error messages:
![image](https://user-images.githubusercontent.com/20326645/62794026-06514080-baa1-11e9-80ad-6477fd60fc28.png)

![image](https://user-images.githubusercontent.com/20326645/62794155-61833300-baa1-11e9-81eb-a703841c033e.png)

When getting the extensions, if the api url hangs, there is a timeout [here](https://github.com/xorye/vscode-quarkus/blob/d5c8414da6230d5b7e5ce32682c8d8a30c0b36ca/src/utils/requestUtils.ts#L26) to take care of that.

Signed-off-by: David Kwon <dakwon@redhat.com>

2019-08-09 16:50 UTC, fbricon commented on src/utils/requestUtils.ts
> +    timeout: 1500
30000ms is more realistic

2019-08-09 19:52 UTC, xorye commented on src/utils/requestUtils.ts
> +    timeout: 1500
changed to 30000ms

2019-08-19 08:52 UTC, fbricon requested changes

2019-08-19 08:52 UTC, fbricon commented on src/generateProject/pickExtensions.ts
> +    state.wizardInterrupted = {reason: 'Unable to reach API endpoint for the extensions list.'};
'Unable to reach '+ apiUrl +'/extensions`

2019-08-19 14:38 UTC, xorye commented
@fbricon I made the changes.

2019-08-19 15:58 UTC, xorye commented
Conflicts are fixed

2019-08-19 17:17 UTC, merged

2019-08-19 17:17 UTC, fbricon commented
Thanks @xorye !