Telemetry on startup/shutdown
redhat-developer/vscode-quarkus pull request #343
Opened 2021-03-24 19:45 UTC by datho7561

Use vscode-commons to collect telemetry data. Telemetry collection is opt-in. Please refer to `USAGE_DATA.md` in this PR for a comprehensive list of what data is collected.

Closes #342

Signed-off-by: David Thompson <davthomp@redhat.com>

2021-03-25 16:21 UTC, rgrunber requested changes
Change looks good overall though.

2021-03-25 16:21 UTC, rgrunber commented on README.md
> +vscode-quarkus extension collects anonymous [usage data](USAGE_DATA.md) and sends it to Red Hat servers to help improve our products and services.
I would add "With your approval, vscode-quarkus extension collects..."

2021-03-25 17:06 UTC, rgrunber approved these changes

2021-03-25 17:12 UTC, merged

2021-04-07 18:34 UTC, rgrunber commented on README.md
> +This extension respects the `redhat.elemetry.enabled` setting, which you can learn more about at https://github.com/redhat-developer/vscode-commons#how-to-disable-telemetry-reporting
@datho7561  Just noticed `elemetry` looking through the vscode-microprofile one. Should correct before releasing.

2021-04-07 18:35 UTC, rgrunber commented on USAGE_DATA.md
> +## What's included in the vscode-xml telemetry data
`vscode-xml` here as well.

2021-04-07 18:50 UTC, datho7561 commented on README.md
> +This extension respects the `redhat.elemetry.enabled` setting, which you can learn more about at https://github.com/redhat-developer/vscode-commons#how-to-disable-telemetry-reporting
#353