Update @redhat-developer/vscode-redhat-telemetry to 0.2.0
redhat-developer/vscode-quarkus pull request #369
Opened 2021-06-23 15:48 UTC by datho7561

Closes #365

Signed-off-by: David Thompson <davthomp@redhat.com>

2021-07-22 23:34 UTC, rgrunber requested changes
I do seem to be getting the warning about vscode-quarkus being unable to register redhat.telemetry.enabled because it's already registered.

Otherwise, startup/shutdown/commands seem to be reported correctly.

2021-07-22 23:34 UTC, rgrunber commented on package.json
> +        "redhat.telemetry.enabled": {
According to https://github.com/redhat-developer/vscode-redhat-telemetry#contribute-the-redhattelemetryenabled-preference , `Unless your extension already depends on a telemetry-enabled Red Hat extension, it needs to declare the redhat.telemetry.enabled preference in its package.json, like:` . So does this need to be here ? This depends on vscode-microprofile, which defines this property.

2021-07-22 23:45 UTC, fbricon commented
No, redhat.telemetry.enabled shouldn't be defined here, as per the doc

Le ven. 23 juil. 2021 à 01:34, Roland Grunberg ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
>
> I do seem to be getting the warning about vscode-quarkus being unable to
> register redhat.telemetry.enabled because it's already registered.
>
> Otherwise, startup/shutdown/commands seem to be reported correctly.
> ------------------------------
>
> In package.json
> <https://github.com/redhat-developer/vscode-quarkus/pull/369#discussion_r675219227>
> :
>
> > @@ -147,6 +146,12 @@
>      "configuration": {
>        "title": "Quarkus Tools",
>        "properties": {
> +        "redhat.telemetry.enabled": {
>
> According to
> https://github.com/redhat-developer/vscode-redhat-telemetry#contribute-the-redhattelemetryenabled-preference
> , Unless your extension already depends on a telemetry-enabled Red Hat
> extension, it needs to declare the redhat.telemetry.enabled preference in
> its package.json, like: . So does this need to be here ? This depends on
> vscode-microprofile, which defines this property.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/redhat-developer/vscode-quarkus/pull/369#pullrequestreview-713303356>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABEJWT64FSFWG344Z2WKQ3TZCTIPANCNFSM47GCTROA>
> .
>

2021-07-23 13:38 UTC, rgrunber commented on src/utils/telemetryUtils.ts
> + * @returns when the telemetry
"when the telemetry event has been sent"

2021-07-23 15:47 UTC, rgrunber approved these changes
Change seems to be working for me. Tested on a vsix.

2021-07-23 15:48 UTC, datho7561 commented
Thanks for the review, Roland!

2021-07-23 15:49 UTC, merged