Update project generation input validation
redhat-developer/vscode-quarkus pull request #77
Opened 2019-09-12 17:07 UTC by xorye

This PR updates the input validation for when you go through the project generation wizard.

![image](https://user-images.githubusercontent.com/20326645/64804738-5a968700-d55d-11e9-9910-6cb139704304.png)

groupId: same as https://code.quarkus.io/
artifactId: same as https://code.quarkus.io/
project version: alphanumeric characters and these symbols: ._-
package name: same as https://code.quarkus.io/
resource name: must start with a letter (capital or lowercase), then, alphanumeric characters and these symbols: ._-

Signed-off-by: David Kwon <dakwon@redhat.com>

2019-09-12 17:08 UTC, xorye commented
The regexes from the validation from https://code.quarkus.io/, are specified in this file: https://github.com/quarkusio/code.quarkus.io/blob/master/src/main/frontend/src/code-quarkus/pickers/__tests__/__snapshots__/info-picker.spec.tsx.snap

2019-09-12 17:15 UTC, fbricon commented
That's good, but how do we handle server-side validation errors? We might lacking behind the server at some point, miss some validation. How are those server side errors managed?

2019-09-12 18:26 UTC, xorye commented
If there is a server side error or a server side validation error, the request() fails and I am able to catch it. I'll implement a warning message

2019-09-12 18:54 UTC, xorye commented
The following message appears when the server doesn't give us a project, which could happen due to many reasons (if we give it invalid parameters, if server is down, if we cannot connect to wifi etc.):

![image](https://user-images.githubusercontent.com/20326645/64812088-879e6600-d56c-11e9-8daa-952defd83059.png)

2019-09-13 17:02 UTC, xorye commented
This PR is still not ready yet. I must continue testing. I'll post an update when things are good.

2019-09-13 18:30 UTC, xorye commented
I think its good now. 

This PR now consists of two commits:
The first commit implements the error message that appears when a project cannot be downloaded from the endpoint for any reason.

The second commit implements client side validation for the inputs from the project generation wizard. It has been updated to match the new changes specified here: https://github.com/quarkusio/code.quarkus.io/pull/142#event-2632554602.

2019-09-16 16:41 UTC, fbricon requested changes

2019-09-16 16:41 UTC, fbricon commented on src/generateProject/validateInput.ts
> +  const re = new RegExp('^[A-Za-z]+[A-Za-z0-9_\\-.]*$');
`-` is not allowed in class names

2019-09-16 18:22 UTC, merged