Generate launch.json tasks.json when needed
redhat-developer/vscode-quarkus pull request #82
Opened 2019-09-17 19:19 UTC by xorye

Fixes #80 

### What this PR does:
When the debug command is called and the debug configuration that starts the quarkus:dev task could not be found, this PR will try to add a new debug configuration (to launch.json) and new quarkus:dev task (to tasks.json).

If the launch.json file already exists, the new debug configuration will be appended to the `configurations` array in the existing launch.json file. If the launch.json file does not exist, a new launch.json file containing the new debug configuration will be created.

Same goes for the quarkus:dev task and the tasks.json file. If the tasks.json file exists, it will append the new task into the `tasks` array. If not, the file is created.

The reason why I added the comment-json npm module was because I wanted to parse a JSON string that contained comments within the JSON. In other words, I wanted to read [these](https://github.com/xorye/vscode-quarkus/tree/80generate_launch_needed/vscode-debug-files) files as a string, then parse it into a javascript object.

Signed-off-by: David Kwon <dakwon@redhat.com>

2019-09-17 19:29 UTC, xorye commented
Not ready yet.

2019-09-17 21:00 UTC, xorye commented
Should be good now.

I had a problem where [`await tasks.fetchTasks()`](https://github.com/microsoft/vscode/blob/86baf839044cd6a886716eb0924bee6d23592f50/src/vs/vscode.d.ts#L5497) from the VSCode api wasn't getting the tasks when the tasks.json was recently created using `fs.writeFileSync()`. 

Now, instead of using `await tasks.fetchTasks()` to get all tasks names, I am using `fs.readFileSync()` to directly read the tasks.json file.

2019-09-18 16:01 UTC, fbricon commented
tslint fails https://travis-ci.org/redhat-developer/vscode-quarkus/jobs/586252796#L555

2019-09-18 16:10 UTC, xorye commented
Fixed

2019-09-18 16:42 UTC, fbricon requested changes

2019-09-18 16:42 UTC, fbricon commented on src/debugging/createDebugConfig.ts
> +function getDebugResource<T>(filename: string): T {
or `return parse(getDebugResourceAsString(filename));`

2019-09-18 16:49 UTC, xorye commented on src/debugging/createDebugConfig.ts
> +function getDebugResource<T>(filename: string): T {
done

2019-09-19 09:41 UTC, merged

2019-09-19 09:43 UTC, fbricon commented
I was able to successfully launch some projects from https://github.com/quarkusio/quarkus-quickstarts. Nice job @xorye!