Debug startup command uses mvn if maven wrapper unavalible
redhat-developer/vscode-quarkus pull request #97
Opened 2019-09-27 20:04 UTC by xorye

Fixes #95

Fixing #95 required some refactoring, most notably the code now uses [WorkspaceConfiguration.update()](https://github.com/microsoft/vscode/blob/6f070c5a354d85afdcd3657b348d8c4d6a1269d4/src/vs/vscode.d.ts#L4183) to create launch.json or tasks.json if those files don't exist.
An example of this is here:

https://github.com/xorye/vscode-quarkus/blob/5331a7dad73bc1c857bb138bbe5b03263b2d008c/src/debugging/createDebugConfig.ts#L91-L92

The benefit of this is that the workspace configuration is being updated right away, which means that we can access tasks.json and launch.json using VSCode API lile so:

```
// get launch config
workspace.getConfiguration('launch', vscode.window.activeTextEditor.document.uri); 

// get tasks
tasks.fetchTasks();
```

Before this PR, launch.json and tasks.json were being created using `fs.writeFileSync()`, which made it so that the workspace configuration wasn't updated right away. Therefore the new tasks/cofigurations weren't immediately accessible with the VSCode API. Instead, the previous code read launch.json and tasks.json manually with `fs.readFileSync()`.

This PR isn't tested on Windows yet.

2019-09-27 20:04 UTC, xorye commented
I will be testing on Windows soon

2019-10-01 19:14 UTC, xorye commented
This PR works on windows.
This PR also considers cases where mvnw exists and mvnw.cmd doesnt (and vice versa).

2019-10-03 09:27 UTC, fbricon requested changes

2019-10-03 09:27 UTC, fbricon commented on src/debugging/CreateDebugConfig.ts
> +    this.tasksJsonDir = this.dotVSCodeDir + '/tasks.json';
not a directory. so tasksJsonFile

2019-10-03 09:27 UTC, fbricon commented on src/debugging/CreateDebugConfig.ts
> +    this.launchJsonDir = this.dotVSCodeDir + '/launch.json';
not a directory. so launchJsonFile

2019-10-03 13:27 UTC, xorye commented
Fixed

2019-10-04 12:28 UTC, merged